[project]
name = "quantum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "rich>=14.2.0",
    "torch>=2.9.0",
]

[tools.basedpyright]

[dependency-groups]
dev = [
    "basedpyright>=1.32.1",
]
