[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quantum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "rich>=14.2.0",
    "matplotlib>=3.9.2",
    "seaborn>=0.13.2",
    "torch>=2.9.0",
    "qiskit-aer>=0.17.2",
]

[project.scripts]
bench = "benchmarks.run:main"
bench-trace = "benchmarks.trace:main"

[tool.hatch.build.targets.wheel]
packages = ["src/quantum", "benchmarks"]

[tool.basedpyright]
reportUnknownMemberType = false

[dependency-groups]
dev = [
    "basedpyright>=1.32.1",
]
compare = [
    "qiskit>=1.3.0",
    "qiskit-aer>=0.16.0",
]
